Insert into SCANHISTORY (SEAT_ID) VALUES ( 1);
Insert into SCANHISTORY (SEAT_ID) VALUES ( 2);
Insert into SCANHISTORY (SEAT_ID) VALUES ( 3);
Insert into SCANHISTORY (SEAT_ID) VALUES ( 4);
Insert into SCANHISTORY (SEAT_ID) VALUES ( 5);
Insert into SCANHISTORY (SEAT_ID) VALUES ( 6);