apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartseat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartseat
  template:
    metadata:
      labels:
        app: smartseat
    spec:
      containers:
        - name: smartseat
          image: smartseat:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: postgresql
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/smartseatDB
            - name: QUARKUS_DATASOURCE_USERNAME
              value: smartseat
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: smartseat_pw
            - name: QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT
              value: import.sql
            - name: QUARKUS_HIBERNATE_ORM_SCHEMA_MANAGEMENT_STRATEGY
              value: drop-and-create
            - name: QUARKUS_HTTP_HOST
              value: 0.0.0.0
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: MP_MESSAGING_INCOMING_PICO_DATA_CONNECTOR
              value: smallrye-mqtt
            - name: MP_MESSAGING_INCOMING_PICO_DATA_HOST
              value: vm90.htl-leonding.ac.at
            - name: MP_MESSAGING_INCOMING_PICO_DATA_PORT
              value: "1883"
            - name: MP_MESSAGING_INCOMING_PICO_DATA_USERNAME
              value: student
            - name: MP_MESSAGING_INCOMING_PICO_DATA_PASSWORD
              value: passme


