quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/smartseatDB
quarkus.datasource.username=smartseat
quarkus.datasource.password=smartseat_pw
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql


quarkus.scheduler.start-mode=forced

quarkus.http.host=0.0.0.0
quarkus.http.port=8080

quarkus.package.jar.type=uber-jar


quarkus.log.level=INFO

mp.messaging.incoming.pico-data.connector=smallrye-mqtt
mp.messaging.incoming.pico-data.host=10.191.112.90
mp.messaging.incoming.pico-data.port=1883
mp.messaging.incoming.pico-data.username=student
mp.messaging.incoming.pico-data.password=passme


quarkus.log.category."at.htl.sockets".level=INFO
quarkus.log.category."at.htl.sockets".handlers=websocket-file
quarkus.log.category."at.htl.sockets".use-parent-handlers=false
quarkus.log.category."at.htl.repository".level=INFO
quarkus.log.category."at.htl.repository".handlers=scheduler
quarkus.log.category."at.htl.repository".use-parent-handlers=false

quarkus.log.handler.file."websocket-file".enable=true
quarkus.log.handler.file."websocket-file".path=.log/websockets.log
quarkus.log.handler.file."websocket-file".level=INFO
quarkus.log.handler.file."websocket-file".format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] %s%e%n
quarkus.log.handler.file."websocket-file".rotation.rotate-on-boot=false
quarkus.log.handler.file."scheduler".enable=true
quarkus.log.handler.file."scheduler".path=.log/scheduler.log
quarkus.log.handler.file."scheduler".level=INFO
quarkus.log.handler.file."scheduler".format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] %s%e%n
quarkus.log.handler.file."scheduler".rotation.max-backup-index=0
quarkus.log.handler.file."scheduler".rotation.rotate-on-boot=false